const pokepalDollData = {
  main: [
    "Pokepal Bulbasaur",
    "Pokepal Charizard",
    "Pokepal Charmander",
    "Pokepal Eevee",
    "Pokepal Gengar",
    "Pokepal Growlithe",
    "Pokepal Jigglypuff",
    "Pokepal Lucario",
    "Pokepal Magikarp",
    "Pokepal Meowth",
    "Pokepal Mew",
    "Pokepal Mewtwo",
    "Pokepal Pikachu",
    "Pokepal Piplup",
    "Pokepal Psyduck",
    "Pokepal Slowpoke",
    "Pokepal Snorlax",
    "Pokepal Squirtle",
    "Pokepal Umbreon",
    "Pokepal Wooper",
    "Pokepal Ash",
    "Pokepal Brock",
    "Pokepal Blastoise",
    "Pokepal Charmeleon",
    "Pokepal Diglett",
    "Pokepal Dragonite",
    "Pokepal Flareon",
    "Pokepal Magnemite",
    "Pokepal Misty",
    "Pokepal Togepi",
    "Pokepal Vaporeon",
    "Pokepal Wartortle",
    "Pokepal Zubat"
  ]
};
