// survival-plushies-data.js
const survivalPlushies = {
  main: [
    "Aerolith",
    "Automaton",
    "Bersorker Orc",
    "Bladeback Orc",
    "Blue Rift Hound",
    "Bubble Slime",
    "Buff Shaman",
    "Crystal Scalemaws",
    "Crystal Slime",
    "Flare Slime",
    "Flash Slime",
    "Fractal",
    "Goblin Foot Soldier",
    "Goblin",
    "Goblin Shadowhunter",
    "Goblin Sharpshooter",
    "Gold Aerolith",
    "Gold Automaton",
    "Gold Bersorker Orc",
    "Gold Bladeback Orc",
    "Gold Bubble Slime",
    "Gold Buff Shaman",
    "Gold Crystal Scalemaws",
    "Gold Crystal Slime",
    "Gold Flare Slime",
    "Gold Flash Slime",
    "Gold Fractal",
    "Gold Goblin Foot Soldier",
    "Gold Goblin",
    "Gold Goblin Shadowhunter",
    "Gold Goblin Sharpshooter",
    "Gold Golem Guardian",
    "Gold Health Shaman",
    "Gold Orc",
    "Gold Quake Slime",
    "Gold Rift Hound",
    "Gold Scalemaw Hatchling",
    "Gold Shield Shaman",
    "Gold Sludge Slime",
    "Gold Standard Slime",
    "Gold Steelguard Orc",
    "Golem Guardian",
    "Health Shaman",
    "Orc",
    "Purple Rift Hound",
    "Quake Slime",
    "Scalemaw Hatchling Green",
    "Scalemaw Hatchling",
    "Shield Shaman",
    "Sludge Slime",
    "Standard Slime",
    "Steelguard Orc Bronze",
    "Steelguard Orc Copper",
    "Steelguard Orc Iron"
  ]
};
