const wrapsData = {
  main: [
    "Akira",
    "Arcanist",
    "Arceus",
    "Azure",
    "Beats",
    "Bee",
    "Blueflame",
    "Camilla",
    "Christmas '24",
    "Crocodile",
    "Crystalline",
    "Deceased",
    "Dragon Soul",
    "Easter 24",
    "Easter 25",
    "Ender Dragon",
    "Evergreen",
    "Fairy",
    "Fallen Angel",
    "Fiend",
    "Frosted",
    "Gamer",
    "Gilded",
    "Gothic Pop",
    "Halloween '24",
    "Heart of the Sea",
    "Independence '24",
    "Inferno",
    "Killburn",
    "Lightning",
    "Little Capybara",
    "Little Cat",
    "Little Dragon",
    "Little Fox",
    "Little Panda",
    "Little Shark",
    "Little Unicorn",
    "Lunar",
    "Lunar 2025",
    "Metallic Edge",
    "Mystic Cyan",
    "Necros",
    "New Years '25",
    "Nitro",
    "Nora",
    "Ocean",
    "Penguin",
    "Petragoras",
    "Royal",
    "Shogun",
    "Spring 2025",
    "St. Patricks",
    "St. Patty's 2025",
    "Summer '24",
    "Sushi",
    "Sweetheart",
    "Teddy",
    "UFO",
    "Valentines 2025",
    "Valerie",
    "Violet",
    "Wild",
    "Wither"
  ]
};
